version: 2

build:
    os: ubuntu-20.04
    tools:
      python: "3.11"
    commands: 
      - mkdir --parents _readthedocs/html/
      - rsync -av --exclude 'readthedocs' --exclude '.git' ./ _readthedocs/html/
