version: 2

build:
    os: ubuntu-20.04
    tools:
      python: "3.11"
    commands: 
      - mkdir --parents _readthedocs/html/
      - cp --recursive $(find . -maxdepth 1 | grep -v readthedocs) _readthedocs/html/
