# .readthedocs.yaml
# Read the Docs configuration file (https://docs.readthedocs.io/en/stable/config-file/v2.html)

version: 2

build:
   os: ubuntu-22.04
   tools:
     python: "3.11"
   apt_packages:
     - gcc
     - g++
     - gfortran
   jobs:
     pre_build:
       - echo "Getting test data"
       - cd tests && python -c "import pynbody.test_utils as tu; tu.precache_test_data()"
       - cd docs && wget -q https://zenodo.org/records/10825178/files/tutorial_gadget4.tar.gz?download=1 -O tutorial_gadget4.tar.gz && tar -xvzf tutorial_gadget4.tar.gz
       - cd docs && wget -q https://zenodo.org/records/10825178/files/tutorial_gadget.tar.gz?download=1 -O tutorial_gadget.tar.gz && tar -xvzf tutorial_gadget.tar.gz
     post_build:
       - mkdir $READTHEDOCS_OUTPUT/html/tutorials/plots/
       - cp -r docs/*.png $READTHEDOCS_OUTPUT/html/tutorials/plots/
       # totally unclear why the above should be necessary - in my own setup, sphinx puts everything in sensible places
       - find $READTHEDOCS_OUTPUT/html  # for debugging
       - find docs/ # for debugging

sphinx:
   configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
