name: fetch-tables.yaml
on:
  workflow_call:

jobs:
  fetch-tables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"

    - name: Install osfclient
      run: |
        python -m pip install osfclient

    - name: Cache table data
      id: cache-tables
      uses: actions/cache@v6
      with:
        path: ionfrac_tables
        key: ionfrac_tables_v1
        enableCrossOsArchive: true

    - name: Fetch table data
      if: steps.cache-tables.outputs.cache-hit != 'true'
      run: |
        osf -p z46rq fetch hm12.npz ionfrac_tables/hm12.npz
        osf -p z46rq fetch fg20.npz ionfrac_tables/fg20.npz
